#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'
require 'mco_env'

environments = McoEnv::Utils.all_environments.sort

active_environment = McoEnv::Utils.active_environment

def usage
  warn <<~DOC
    usage:
        mcoenv
        mcoenv local <environment>
  DOC
  exit(1)
end

if ARGV.empty?
  lister = McoEnv::Lister.new
  lister.add('system', active_environment.nil?)
  environments.each do |environment|
    lister.add(environment, environment == active_environment)
  end
  lister.print
else
  case ARGV.shift
  when 'local'
    if ARGV[0] == 'system'
      FileUtils.rm_f('.mco-environment')
    elsif environments.include?(ARGV[0])
      File.open('.mco-environment', 'w') do |f|
        f.puts ARGV[0]
      end
    else
      raise "Unknown environment #{ARGV[0]}"
    end
  else
    usage
  end
end
