#!/usr/bin/env ruby

require 'fileutils'
require 'mco_env'

environments = McoEnv::Utils.all_environments.sort

active_environment = McoEnv::Utils.active_environment

def usage
  $stderr.puts <<~DOC
    usage:
        mcoenv
        mcoenv local <environment>
    DOC
  exit(1)
end

if ARGV.empty?
  environments.each do |environment|
    puts format(' %c %s', (environment == active_environment) ? '*' : ' ', environment)
  end
  puts format(' %c %s', (active_environment.nil?) ? '*' : ' ', 'system')
else
  case ARGV.shift
  when 'local'
    if ARGV[0] == 'system'
      FileUtils.rm_f('.mco-environment')
    elsif environments.include?(ARGV[0])
    File.open('.mco-environment', 'w') do |f|
      f.puts ARGV[0]
    end
    else
      raise "Unknown environment #{ARGV[0]}"
    end
  else
    usage
  end
end
